on:
  release:
    types:
    - released

jobs:

  publish-opam-package:
    uses: ./.github/workflows/publish-opam.yml
    with:
      tag: ${{ github.ref_name }}
      prerelease: ${{ github.event.release.prerelease }}
      prerelease_secondary_opam_file: vcoq-language-server.opam
    secrets: inherit
